apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml
- service.yaml
- service_account.yaml

configMapGenerator:
- files:
  - config.yaml
  name: config
  options:
    disableNameSuffixHash: true
