apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - name: workload-services-metrics
    options:
      labels:
        telemetry.datumapis.com/resource-metrics-config: "true"

    files:
      - instances.yaml
      - workload-deployments.yaml
      - workloads.yaml
