kind: CustomResourceStateMetrics
spec:
  resources:
    - groupVersionKind:
        group: compute.datumapis.com
        kind: Workload
        version: v1alpha
      metricNamePrefix: "workload"
      labelsFromPath:
        namespace: [metadata, namespace]
        name: [metadata, name]
      metrics:
        - name: "info"
          help: "Information about workload"
          each:
            type: Info
            info:
              labelsFromPath:
                uid: [metadata, uid]
        - name: "status_condition"
          help: "The current status conditions of the workload"
          each:
            type: Gauge
            gauge:
              path: [status, conditions]
              labelsFromPath:
                condition: [type]
                reason: [reason]
                status: [status]
              valueFrom: [status]
