---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-compute-datumapis-com-v1alpha-workload
  failurePolicy: Fail
  name: mworkload.kb.io
  rules:
  - apiGroups:
    - compute.datumapis.com
    apiVersions:
    - v1alpha
    operations:
    - CREATE
    - UPDATE
    resources:
    - workloads
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-compute-datumapis-com-v1alpha-workload
  failurePolicy: Fail
  name: vworkload.kb.io
  rules:
  - apiGroups:
    - compute.datumapis.com
    apiVersions:
    - v1alpha
    operations:
    - CREATE
    - UPDATE
    resources:
    - workloads
  sideEffects: None
