# permissions for end users to view workloaddeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: workload-operator
    app.kubernetes.io/managed-by: kustomize
  name: workloaddeployment-viewer-role
rules:
- apiGroups:
  - compute.datumapis.com
  resources:
  - workloaddeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - compute.datumapis.com
  resources:
  - workloaddeployments/status
  verbs:
  - get
