apiVersion: multicluster.x-k8s.io/v1alpha1
kind: ClusterProfile
metadata:
 name: local-cluster
 namespace: default
 labels:
   x-k8s.io/cluster-manager: local-cluster-manager
spec:
  displayName: local-cluster
  clusterManager:
    name: local-cluster-manager
