apiVersion: apiserver.config.datumapis.com/v1alpha1
kind: WorkloadOperator
metricsServer:
  bindAddress: "0"

webhookServer:
  tls:
    secretRef:
      name: workload-operator-webhook-server-cert
      namespace: kube-system
